---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sloth.fullname" . }}
  labels:
    {{- include "sloth.labels" . | nindent 4 }}
rules:
  - apiGroups: ["sloth.slok.dev"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["deckhouse.io"]
    resources: ["customprometheusrules"]
    verbs: ["create", "list", "get", "update", "watch"]
